### ISSUE TITLE
Ack doesn't search zero length files

### ISSUE THREAD

**Issue by bitsed** [beyondgrep/ack1#102] opened 2009-10-19 19:26 UTC
Some operating systems (notably Linux) provide zero length files containing system information.  Ack version 1.90 doesn't work with these files since it skips searching of all zero length files.  The patch below attempts to address this issue.

<pre>
--- /usr/bin/ack        2009-10-19 11:14:59.919362762 -0700
+++ bin/ack     2009-10-19 11:57:05.632362838 -0700        
@@ -2481,21 +2481,24 @@                                    
                                                           
     return 1 if $opt->{v};                                

-    my $size = -s $self->{fh};
-    if ( $size == 0 ) {
-        return 0;
-    }
-    elsif ( $size > 100_000 ) {
-        return 1;
+    if ( -s $self->{fh} > 100_000 ) {
+       return 1;
     }

     my $buffer;
-    my $rc = sysread( $self->{fh}, $buffer, $size );
+    my $size;
+    my $rc;
+    do {
+        my $inbuf;
+        $size += $rc = sysread( $self->{fh}, $inbuf, 100_000 );
+        $buffer .= $inbuf;
+    } while ($rc != 0);
+
     if ( not defined $rc ) {
         App::Ack::warn( "$self->{filename}: $!" );
         return 1;
     }
-    return 0 unless $rc && ( $rc == $size );
+    return 0 unless $size;

     my $regex = $opt->{regex};
     return $buffer =~ /$regex/m;
</pre>

**Comment by petdance** [comment] 2009-10-19 19:36
I don't understand why it would be bad to not search 0-length files.

**Comment by bitsed** [comment] 2009-10-19 19:48
I think it's not searching zero length files that don't match.

**Comment by bitsed** [comment] 2009-10-19 19:57
This issue looks like it's a duplicate of issue 89.

**Comment by hoelzro** [comment] 2013-08-28 21:40
Closing as duplicate of #89.

**Closed as completed by hoelzro** 2013-08-28 21:40 UTC
