### ISSUE TITLE
--ignore-dir=../foo doesn't ignore files from ../foo/

### ISSUE THREAD

**Issue by ingmarv** [beyondgrep/ack1#103] opened 2009-10-30 00:46 UTC
ingmar@cannonball ~/development/exherbo/repositories/arbor (git)-[master]- % ack --ignore-dir=../multilib/ _gcc-specs-exists ../
../multilib/exlibs/toolchain-funcs.exlib
219:# function for use by _gcc-specs-exists (for flag-o-matic).
228:_gcc-specs-exists() {

**Comment by eendeego** [comment] 2012-01-02 20:31
There's a bug on option parsing specifying the actual parameter as "--ignore-dirs" (note the plural); everywhere else on the code specifies "--ignore-dir".

I can't get it to work either.

(Note: This is reported against ack 1.96)

**Comment by hoelzro** [comment] 2013-08-28 21:18
Duplicate of #216 (or it's a duplicate of this one ;) )

**Closed as completed by hoelzro** 2013-08-28 21:18 UTC
